puts "MATRICI"
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ARIA" ).try(:id), title: "PTS (Polveri Totali Sospese)", radia: 38, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ARIA" ).try(:id), title: "PM10 (Polveri con diametro < 10mm)", radia: 39, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ARIA" ).try(:id), title: "FRAZIONE GASSOSA", radia: 40, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ARIA" ).try(:id), title: "PM2.5 (Polveri con diametro < 2.5mm)", radia: 744, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DEPOSIZIONE" ).try(:id), title: "FALLOUT TOTALE", radia: 41, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DEPOSIZIONE" ).try(:id), title: "FALLOUT UMIDO", radia: 42, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DEPOSIZIONE" ).try(:id), title: "FALLOUT SECCO", radia: 43, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DEPOSIZIONE" ).try(:id), title: "PIOGGIA", radia: 44, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DEPOSIZIONE" ).try(:id), title: "NEVE DISCIOLTA", radia: 45, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "RADIAZIONE ESTERNA" ).try(:id), title: "EQUIVALENTE DI DOSE AMBIENTE (Sv/h) (ex 'dose gamma in aria' ) ", radia: 46, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "RADIAZIONE ESTERNA" ).try(:id), title: "DOSE GAMMA ASSORBITA  IN ARIA (Gy/h)", radia: 1064, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUE SUPERFICIALI" ).try(:id), title: "ACQUA DI CORSO D'ACQUA SUPERFICIALE", radia: 47, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUE SUPERFICIALI" ).try(:id), title: "ACQUA DI CORSO D'ACQUA SUPERFICIALE (FILTRI)", radia: 240, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUE SUPERFICIALI" ).try(:id), title: "ACQUA DI CORSO D'ACQUA SUPERFICIALE (NCFC)", radia: 250, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUE SUPERFICIALI" ).try(:id), title: "ACQUA DI CORSO D'ACQUA SUPERFICIALE (RESINE MISTE)", radia: 251, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUE SUPERFICIALI" ).try(:id), title: "ACQUA DI LAGO", radia: 48, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUE SUPERFICIALI" ).try(:id), title: "ACQUA DI ZONE MARINO COSTIERE", radia: 49, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUE SUPERFICIALI" ).try(:id), title: "ACQUA DI ZONE MARINO COSTIERE (NCFC)", radia: 252, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUE SUPERFICIALI" ).try(:id), title: "ACQUA DI ZONE MARINO COSTIERE (SALE)", radia: 273, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUE SUPERFICIALI" ).try(:id), title: "ACQUA DI ZONE DI TRANSIZIONE", radia: 50, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUE SUPERFICIALI" ).try(:id), title: "ACQUA DI LAGO ARTIFICIALE", radia: 51, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUE SUPERFICIALI" ).try(:id), title: "ACQUA DI CANALE ARTIFICIALE", radia: 52, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUE SUPERFICIALI" ).try(:id), title: "ACQUA DI GHIACCIAIO", radia: 53, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUE SOTTERRANEE" ).try(:id), title: "ACQUA DI FALDA FREATICA", radia: 54, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUE SOTTERRANEE" ).try(:id), title: "ACQUA DI FALDA PROFONDA", radia: 55, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUE SOTTERRANEE" ).try(:id), title: "ACQUA DI SORGENTE", radia: 56, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUOLO" ).try(:id), title: "SUOLO DI BRUGHIERA", radia: 60, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUOLO" ).try(:id), title: "SUOLO DI MACCHIA MEDITERRANEA", radia: 61, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUOLO" ).try(:id), title: "SUOLO DI PASCOLO ", radia: 58, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUOLO" ).try(:id), title: "SUOLO DI RISAIA", radia: 1319, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUOLO" ).try(:id), title: "SUOLO DI TORBIERA ", radia: 59, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUOLO" ).try(:id), title: "SUOLO DI ZONE BOSCATE", radia: 57, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUOLO" ).try(:id), title: "SUOLO INDISTURBATO", radia: 745, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUOLO" ).try(:id), title: "SUOLO INDISTURBATO 0-5 CM", radia: 246, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUOLO" ).try(:id), title: "SUOLO INDISTURBATO 5-10 CM", radia: 247, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUOLO" ).try(:id), title: "SUOLO INDISTURBATO 10-15 CM", radia: 248, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUOLO" ).try(:id), title: "SUOLO COLTIVATO", radia: 221, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SEDIMENTO" ).try(:id), title: "DMOS (Detrito minerale organico sedimentabile)", radia: 64, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SEDIMENTO" ).try(:id), title: "SABBIA DI MARE", radia: 1316, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SEDIMENTO" ).try(:id), title: "SEDIMENTO ACQUA TRANSIZIONE", radia: 66, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SEDIMENTO" ).try(:id), title: "SEDIMENTO FLUVIALE", radia: 63, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SEDIMENTO" ).try(:id), title: "SEDIMENTO LACUSTRE", radia: 62, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SEDIMENTO" ).try(:id), title: "SEDIMENTO MARINO COSTIERO", radia: 65, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SEDIMENTO" ).try(:id), title: "CRIOCONITE", radia: 760, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "VEGETAZIONE ACQUA DOLCE" ).try(:id), title: "MACROPHYTON", radia: 67, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "VEGETAZIONE ACQUA DOLCE" ).try(:id), title: "MACROPHYTON (Elodea canadensis)", radia: 68, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "VEGETAZIONE ACQUA DOLCE" ).try(:id), title: "MACROPHYTON (Potamogeton gramineus)", radia: 69, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "VEGETAZIONE ACQUA DOLCE" ).try(:id), title: "PERIPHYTON", radia: 70, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "VEGETAZIONE ACQUA DOLCE" ).try(:id), title: "SCIRPUS LACUSTRIS", radia: 237, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "VEGETAZIONE ACQUA DOLCE" ).try(:id), title: "SPARGANIUM ERECTUM", radia: 238, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "VEGETAZIONE MARINA" ).try(:id), title: "ALGHE ", radia: 71, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "VEGETAZIONE MARINA" ).try(:id), title: "ALGA (Ulva rigida)", radia: 72, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "VEGETAZIONE MARINA" ).try(:id), title: "ALGA (Ulva lactuca)", radia: 73, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "VEGETAZIONE MARINA" ).try(:id), title: "FANEROGAMA (Posidonia oceanica)", radia: 74, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MUSCHIO" ).try(:id), title: "PLEUROCARPO (Ctenidium molluscum)", radia: 75, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MUSCHIO" ).try(:id), title: "PLEUROCARPO (Hypnum cupressiforme)", radia: 76, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MUSCHIO" ).try(:id), title: "PLEUROCARPO (Homalotecium sericium)", radia: 77, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "LATTUGA", radia: 78, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "SPINACI", radia: 79, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "BIETOLE", radia: 80, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "CICORIA", radia: 81, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "INDIVIA", radia: 82, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "ASPARAGI", radia: 83, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "RADICCHIO", radia: 84, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "CAVOLO CAPPUCCIO", radia: 604, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "CAVOLO VERZA", radia: 605, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "FINOCCHI", radia: 317, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "INSALATA BRASILIANA", radia: 606, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "PORRI", radia: 607, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "CIME DI RAPA", radia: 427, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "SEDANO", radia: 345, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "ALLORO", radia: 439, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI E VEGETALI A FOGLIA E STELO" ).try(:id), title: "VALERIANA", radia: 444, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A RADICE BULBO TUBERO" ).try(:id), title: "AGLIO", radia: 88, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A RADICE BULBO TUBERO" ).try(:id), title: "CAROTE", radia: 86, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A RADICE BULBO TUBERO" ).try(:id), title: "CIPOLLE", radia: 87, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A RADICE BULBO TUBERO" ).try(:id), title: "PATATE", radia: 85, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A RADICE BULBO TUBERO" ).try(:id), title: "RAPE", radia: 550, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A RADICE BULBO TUBERO" ).try(:id), title: "RAVANELLI", radia: 498, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A RADICE BULBO TUBERO" ).try(:id), title: "SCALOGNO", radia: 1311, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A FRUTTO E FIORE" ).try(:id), title: "CARCIOFI", radia: 93, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A FRUTTO E FIORE" ).try(:id), title: "CAVOLFIORI", radia: 92, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A FRUTTO E FIORE" ).try(:id), title: "CAVOLINI DI BRUXELLES", radia: 1310, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A FRUTTO E FIORE" ).try(:id), title: "CAVOLO BROCCOLO", radia: 370, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A FRUTTO E FIORE" ).try(:id), title: "CETRIOLI", radia: 324, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A FRUTTO E FIORE" ).try(:id), title: "MELANZANE", radia: 90, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A FRUTTO E FIORE" ).try(:id), title: "PEPERONI", radia: 94, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A FRUTTO E FIORE" ).try(:id), title: "SEMI DI PEPERONE", radia: 271, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A FRUTTO E FIORE" ).try(:id), title: "POMODORI", radia: 89, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A FRUTTO E FIORE" ).try(:id), title: "SEMI DI POMODORO", radia: 272, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A FRUTTO E FIORE" ).try(:id), title: "SEMI DI GIRASOLE", radia: 274, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A FRUTTO E FIORE" ).try(:id), title: "ZUCCA", radia: 1312, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ORTAGGI A FRUTTO E FIORE" ).try(:id), title: "ZUCCHINE", radia: 91, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LEGUMI" ).try(:id), title: "FAGIOLI", radia: 95, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LEGUMI" ).try(:id), title: "PISELLI", radia: 96, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LEGUMI" ).try(:id), title: "FAVE", radia: 339, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LEGUMI" ).try(:id), title: "LENTICCHIE", radia: 97, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LEGUMI" ).try(:id), title: "CECI", radia: 98, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LEGUMI" ).try(:id), title: "SOIA", radia: 354, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LEGUMI" ).try(:id), title: "FAGIOLINI", radia: 608, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "ALBICOCCHE", radia: 307, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "ANANAS", radia: 336, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "ANGURIA", radia: 1084, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "ARACHIDI", radia: 1105, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "ARANCE", radia: 101, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "BANANE", radia: 358, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "CACAO", radia: 351, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "CACHI", radia: 609, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "CASTAGNE", radia: 300, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "CILIEGIE", radia: 385, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "CLEMENTINE", radia: 1318, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "DATTERI", radia: 1284, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "FICHI", radia: 415, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "FRAGOLE", radia: 610, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "KIWI", radia: 321, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "LIMONI", radia: 312, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "MANDARINI", radia: 319, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "MANDORLE", radia: 543, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "MELE", radia: 99, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "MELONI", radia: 311, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "NESPOLE", radia: 1106, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "NOCCIOLE", radia: 316, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "NOCI", radia: 310, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "PERE", radia: 100, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "PESCHE", radia: 102, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "PISTACCHI", radia: 487, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "POMPELMI", radia: 426, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "PRUGNE", radia: 488, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "UVA", radia: 309, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "UVA SULTANINA", radia: 1304, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "GHIANDE", radia: 756, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FRUTTA" ).try(:id), title: "SORBO", radia: 757, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CEREALI" ).try(:id), title: "AVENA", radia: 329, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CEREALI" ).try(:id), title: "GRANO TENERO", radia: 103, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CEREALI" ).try(:id), title: "GRANO DURO", radia: 104, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CEREALI" ).try(:id), title: "MAIS", radia: 105, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CEREALI" ).try(:id), title: "RISO", radia: 106, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CEREALI" ).try(:id), title: "ORZO", radia: 301, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CEREALI" ).try(:id), title: "FARRO", radia: 616, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AGARICUS ARVENSIS", radia: 617, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AGARICUS AUGUSTUS", radia: 620, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AGARICUS MACROSPORUS", radia: 621, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AGARICUS SILVICOLA", radia: 622, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "ALBATRELLUS CRISTATUS", radia: 623, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "ALBATRELLUS OVINUS", radia: 624, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AMANITA CAESAREA", radia: 625, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AMANITA FRANCHETII", radia: 626, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AMANITA RUBESCENS", radia: 627, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "ARMILLARIA MELLEA", radia: 628, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETINUS CAVIPES", radia: 629, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETINUS LANDKAMMERI", radia: 630, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS AEREUS", radia: 631, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS AESTIVALIS", radia: 632, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS ELEGANS o SUILLUS GREVILLEI", radia: 633, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS PINOPHILUS", radia: 634, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS QUELETII", radia: 635, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS REGIUS", radia: 636, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CALOCYBE GAMBOSA", radia: 637, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CANTHARELLUS LUTESCENS", radia: 638, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CANTHARELLUS MELANOXEROS", radia: 639, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CANTHARELLUS TUBAEFORMIS", radia: 640, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CHAMPIGNON (Agaricus bisporus)", radia: 110, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CLITOCYBE DEALBATA", radia: 641, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CLITOCYBE GIBBA", radia: 642, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CLITOCYBE NEBULARIS", radia: 643, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CLITOPILUS PRUNULUS", radia: 644, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "COLLYBIA ASEMA", radia: 645, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "COLLYBIA FUSIPES", radia: 646, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CORTINARIUS CAMPHORATUS", radia: 647, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CORTINARIUS PRAESTANS", radia: 648, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CORTINARIUS TRAGANUS", radia: 649, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CORTINARIUS VIOLACEUS", radia: 650, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CRATERELLUS CORNUCOPIOIDES", radia: 651, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "ENTOLOMA NIPHOIDES", radia: 652, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "ENTOLOMA SEPIUM", radia: 653, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "GALLETTI COLTIVATI (Cantharellus cibarius)", radia: 109, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "GALLETTI SPONTANEI (Cantharellus cibarius)", radia: 108, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "GOMPHUS CLAVATUS", radia: 654, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "HYDNUM REPANDUM", radia: 655, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LACTARIUS DELICIOSUS", radia: 656, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LACTARIUS DETERRIMUS", radia: 657, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LACTARIUS PORNINSIS", radia: 658, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LACTARIUS RUFUS", radia: 659, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LACTARIUS SANGUIFLUS", radia: 235, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AGARICUS BERNARDIFORMIS", radia: 276, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AGARICUS MACROCARPUS", radia: 277, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AGARICUS CAMPESTRIS", radia: 278, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AGARICUS ALBERTII", radia: 279, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AGROCYBE AEGERITA", radia: 280, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AMANITA CITRINA", radia: 281, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AMANITA UMBRINOLUTEA", radia: 282, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AMANITA LIVIDOPALLESCENS", radia: 283, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AMANITA VAGINATA", radia: 284, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AMANITA SPISSA", radia: 285, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AMANITA MUSCARIA", radia: 286, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "ARMILLARIA TABESCENS", radia: 287, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS CALOPUS", radia: 288, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS RHODOPURPUREUS", radia: 289, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS FECHTNERI", radia: 290, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS BRUNNEUS", radia: 291, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS RHODOXANTHUS", radia: 292, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS SUBAPPENDICULATUS", radia: 293, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS LURIDUS", radia: 294, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS ERYTHROPUS", radia: 295, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CLYTOCIBE CONNATA", radia: 296, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "COLLYBIA ACERVATA", radia: 297, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "COLLYBIA DRYOPHILA", radia: 298, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "COLLYBIA BUTIRACEA", radia: 299, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CORTINARIUS INFRACTUS", radia: 304, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "COPRINUS COMATUS", radia: 313, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CHOIROMYCES MEANDRIFONDIS", radia: 323, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CHROOGOMPHUS RUTILUS", radia: 327, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "ENTOLOMA APRILE", radia: 331, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "ENTOLOMA CLYPEATUM", radia: 332, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "ERICIUS ERINACEUS", radia: 334, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "GYMNOPILUS HYBRIDUS", radia: 340, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "HYGROPHORUS PENARIUS", radia: 347, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "HYGROPHORUS EBURNEUS", radia: 356, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "HYGROPHROPSIS RUTILANS ", radia: 359, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "HYPHOLOMA FASCICULARE", radia: 451, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "HYPHOLOMA SUBLATERITIUM", radia: 453, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LACTARIUS GLAUCESCENS", radia: 529, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LACTARIUS PERGAMENUS", radia: 551, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LACTARIUS VOLEMUS", radia: 552, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LAETIPORUS SULPHUREUS", radia: 553, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LACTARIUS PIPERATUS", radia: 554, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LACCARIA LACCATA", radia: 555, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LECCINUM QUERCINUM", radia: 556, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LECCINUM DURIUSCULUM", radia: 557, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LEPISTA NEBULARIS", radia: 558, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LECOAGARICUS LEUCOTHITES", radia: 559, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LYOPYLLUM FUMOSUM", radia: 560, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "MACROLEPIOTA KONRADI", radia: 561, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "MACROLEPIOTA GRACILENTA", radia: 562, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "MYCENA ROSEA", radia: 563, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "MYCENA PURA", radia: 564, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "MERIPILUS GIGANTEUS", radia: 565, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "MORCHELLA CONICA", radia: 566, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "PLUTEUS CERVINUS", radia: 567, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "OMPHALOTUS OLEARIUS", radia: 568, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RAMARIA LUTEA", radia: 569, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RAMARIA ABETINA", radia: 570, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA SARDONIA", radia: 571, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA VINOSOBRUNNEA", radia: 572, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA CHLOROIDES", radia: 573, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA XERAMPELLINA", radia: 574, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA FELLEA", radia: 575, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA MACULATA", radia: 576, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA ALUTACEA", radia: 577, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA SERICATULA", radia: 578, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA RUBROALBA", radia: 579, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA ALBONIGRA", radia: 580, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA IONOCHCLORA", radia: 581, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA OLIVACEA", radia: 752, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "SUILLUS LUTEUS", radia: 582, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "SUILLUS GRANULATUS", radia: 583, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "TRICHOLOMA SEJUNCTUM", radia: 584, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "TRICHOLOMA USTALOIDES", radia: 585, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "TRICHOLOMA ALBUM", radia: 586, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "TRICHOLOMA ACERBUM", radia: 587, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "TRICHOLOMOPSIS RUTILANS", radia: 588, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "XEROCOMUS SUBTOMENTOSUS", radia: 589, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "XEROCOMUS COMUNIS", radia: 590, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "XERULA RADICATA", radia: 591, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LACTARIUS SALMONICOLOR", radia: 1110, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LACTARIUS SCROBICULATUS", radia: 660, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LECCINUM AURANTIACUM", radia: 661, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LECCINUM CARPINI", radia: 662, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LECCINUM VERSIPELLE", radia: 663, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LECCINUM SCABRUM", radia: 733, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "FISTULINA HEPATICA", radia: 734, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LENTINUS EDODES", radia: 664, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LEPISTA NUDA", radia: 665, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LYOPHYLLUM CONNATUM", radia: 666, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LYOPHYLLUM DECASTES", radia: 667, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "MACROLEPIOTA PERMIXTA", radia: 668, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "MACROLEPIOTA PROCERA", radia: 669, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "MARASMIUS SCORODONIUS", radia: 1109, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "PAXILLUS INVOLUTUS", radia: 670, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "PORCINI SPONTANEI (Boletus edulis)", radia: 107, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RAMARIA AUREA", radia: 671, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "ROZITES CAPERATUS", radia: 672, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA AUREA", radia: 673, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA CUTEFRACTA", radia: 674, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA CYANOXANTHA", radia: 675, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA DECOLORANS", radia: 676, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA DELICA", radia: 677, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA PALUDOSA", radia: 678, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA SUBFOETENS", radia: 679, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA VINOSA", radia: 680, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "SARCODON IMBRICATUS", radia: 681, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "SUILLUS TRIDENTINUS", radia: 682, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "SUILLUS VARIEGATUS", radia: 683, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "SUILLUS VISCIDUS", radia: 684, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "TRICHOLOMA SAPONACEUM", radia: 685, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "TRICHOLOMA TERREUM", radia: 686, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "TRICHOLOMA VACCINUM", radia: 687, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS BADIUS o XEROCOMUS BADIUS", radia: 688, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "XEROCOMUS FERRUGINEUS", radia: 689, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "TYLOPILUS FELLEUS", radia: 1145, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LACTARIUS TRIVIALIS", radia: 1146, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "TRICHOLOMA STIPAROPHYLLUM", radia: 1147, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "XEROCOMUS PRUINATUS", radia: 690, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "LACTARIUS SPP", radia: 598, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "HELVELLA CRISPA", radia: 599, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "AGARICUS XANTHODERMUS", radia: 600, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "HYGROPHORUS RUSSULA", radia: 601, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RAMARIA PALLIDA", radia: 602, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RAMARIA FLAVESCENS  ", radia: 603, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "TRICHOLOMA SCIODES", radia: 611, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "MACROLEPIOTA MASTOIDEA", radia: 612, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "PLEUROTUS ERYNGI", radia: 613, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "GRIFOLA FRONDOSA", radia: 614, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "SUILLUS COLLINITUS", radia: 615, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "CORTINARIUS ORICHALCEUS", radia: 618, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "BOLETUS IMPOLITUS", radia: 619, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "RUSSULA MUSTELINA", radia: 737, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "ALBATRELLUS CONFLUENS", radia: 738, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "ARMILLARIA OSTOYAE", radia: 758, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "MARASMIUS OREADES", radia: 759, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FUNGHI" ).try(:id), title: "PLEUROTUS OSTREATUS", radia: 768, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DERIVATI CEREALI" ).try(:id), title: "FARINA GRANO TENERO", radia: 111, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DERIVATI CEREALI" ).try(:id), title: "FARINA GRANO DURO", radia: 112, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DERIVATI CEREALI" ).try(:id), title: "PASTA", radia: 113, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DERIVATI CEREALI" ).try(:id), title: "PANE", radia: 114, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DERIVATI CEREALI" ).try(:id), title: "FARINA GRANTURCO", radia: 691, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DERIVATI CEREALI" ).try(:id), title: "FARINA RISO", radia: 692, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DERIVATI CEREALI" ).try(:id), title: "FARINA SEGALE", radia: 693, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DERIVATI CEREALI" ).try(:id), title: "FARINA DI FARRO", radia: 764, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "GRASSI VEGETALI" ).try(:id), title: "OLIO D'OLIVA", radia: 115, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "GRASSI VEGETALI" ).try(:id), title: "OLIO DI SEMI DI MAIS", radia: 694, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "GRASSI VEGETALI" ).try(:id), title: "OLIO DI SEMI DI ARACHIDE", radia: 1306, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "GRASSI VEGETALI" ).try(:id), title: "OLIO DI SEMI DI GIRASOLE", radia: 1307, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "GRASSI VEGETALI" ).try(:id), title: "OLIO DI SEMI VARI", radia: 1308, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "GRASSI VEGETALI" ).try(:id), title: "OLIO DI SOIA", radia: 1309, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BEVANDE" ).try(:id), title: "BIRRA", radia: 117, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BEVANDE" ).try(:id), title: "CAFFE' LIQUIDO O IN POLVERE", radia: 392, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BEVANDE" ).try(:id), title: "COLA", radia: 118, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BEVANDE" ).try(:id), title: "MOSTO D'UVA", radia: 1305, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BEVANDE" ).try(:id), title: "SUCCO DI MELE", radia: 214, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BEVANDE" ).try(:id), title: "SUCCO DI MIRTILLI", radia: 215, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BEVANDE" ).try(:id), title: "SUCCO DI PERE", radia: 213, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BEVANDE" ).try(:id), title: "SUCCO DI PESCHE", radia: 249, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BEVANDE" ).try(:id), title: "VINO", radia: 116, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BEVANDE" ).try(:id), title: "VINO - LAMBRUSCO", radia: 253, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BEVANDE" ).try(:id), title: "VINO - SANGIOVESE", radia: 254, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BEVANDE" ).try(:id), title: "VINO - ALBANA", radia: 255, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BEVANDE" ).try(:id), title: "VINO - PIGNOLETTO", radia: 256, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BEVANDE" ).try(:id), title: "VINO - TREBBIANO", radia: 257, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FORAGGIO" ).try(:id), title: "ERBA MEDICA", radia: 119, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FORAGGIO" ).try(:id), title: "ERBA", radia: 1315, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FORAGGIO" ).try(:id), title: "FIENO", radia: 436, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FORAGGIO" ).try(:id), title: "VECCIA COMUNE (Vicia sativa)", radia: 736, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FORAGGIO" ).try(:id), title: "TRIFOGLIO", radia: 120, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "FORAGGIO" ).try(:id), title: "MANGIME UNIFEED", radia: 761, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BOVINO" ).try(:id), title: "MUSCOLO BOVINO", radia: 121, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BOVINO" ).try(:id), title: "MUSCOLO BOVINO - VITELLONE", radia: 258, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BOVINO" ).try(:id), title: "FEGATO BOVINO", radia: 122, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BOVINO" ).try(:id), title: "INTERIORA BOVINO", radia: 123, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BOVINO" ).try(:id), title: "OSSA BOVINO", radia: 124, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BOVINO" ).try(:id), title: "TIROIDE BOVINO", radia: 125, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUINO" ).try(:id), title: "MUSCOLO SUINO", radia: 126, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUINO" ).try(:id), title: "FEGATO SUINO", radia: 127, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUINO" ).try(:id), title: "INTERIORA SUINO", radia: 128, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUINO" ).try(:id), title: "OSSA SUINO", radia: 129, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "SUINO" ).try(:id), title: "TIROIDE SUINO", radia: 130, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "OVINO" ).try(:id), title: "MUSCOLO OVINO", radia: 131, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "OVINO" ).try(:id), title: "FEGATO OVINO", radia: 132, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "OVINO" ).try(:id), title: "INTERIORA OVINO", radia: 133, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "OVINO" ).try(:id), title: "OSSA OVINO", radia: 134, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "OVINO" ).try(:id), title: "TIROIDE OVINO ", radia: 135, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "POLLAME" ).try(:id), title: "MUSCOLO POLLO", radia: 136, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "POLLAME" ).try(:id), title: "UOVO GALLINA", radia: 137, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "POLLAME" ).try(:id), title: "MUSCOLO TACCHINO", radia: 138, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "POLLAME" ).try(:id), title: "FARAONA", radia: 596, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CONIGLIO" ).try(:id), title: "MUSCOLO CONIGLIO", radia: 203, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "EQUINO" ).try(:id), title: "MUSCOLO EQUINO", radia: 201, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CACCIAGIONE" ).try(:id), title: "MUSCOLO LEPRE", radia: 139, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CACCIAGIONE" ).try(:id), title: "MUSCOLO CINGHIALE", radia: 140, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CACCIAGIONE" ).try(:id), title: "MUSCOLO CERVO", radia: 141, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CACCIAGIONE" ).try(:id), title: "FEGATO DI CINGHIALE", radia: 695, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CACCIAGIONE" ).try(:id), title: "CARCASSA DI CINGHIALE", radia: 742, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CACCIAGIONE" ).try(:id), title: "FECI DI CINGHIALE", radia: 743, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CACCIAGIONE" ).try(:id), title: "INTESTINO DI CINGHIALE", radia: 753, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CACCIAGIONE" ).try(:id), title: "TESTA DI CINGHIALE", radia: 754, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CACCIAGIONE" ).try(:id), title: "POLMONE DI CINGHIALE", radia: 755, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CACCIAGIONE" ).try(:id), title: "SALAME DI CINGHIALE", radia: 763, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CACCIAGIONE" ).try(:id), title: "MUSCOLO CAMOSCIO", radia: 696, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CACCIAGIONE" ).try(:id), title: "MUSCOLO CAPRIOLO", radia: 697, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CACCIAGIONE" ).try(:id), title: "MUSCOLO GERMANO REALE (Anas platyrhynchos)", radia: 698, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CACCIAGIONE" ).try(:id), title: "FEGATO DI CAPRIOLO", radia: 1104, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CACCIAGIONE" ).try(:id), title: "POLMONE DI CAPRIOLO", radia: 1107, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "AGONE (Alosa fallax lacustris)", radia: 700, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "ALBORELLA (Alburnus alburnus alborella)", radia: 142, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "ASPIO (Aspius aspius)", radia: 701, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "BARBO (Barbus plebejus)", radia: 702, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "BOTTATRICE (Lota lota)", radia: 703, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "CARASSIO (Carassius carassius)", radia: 217, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "CARPA (Cyprinus Carpio)", radia: 218, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "CAVEDANO (Leuciscus cephalus)", radia: 704, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "LAVARELLO o COREGONE (Coregonus lavaretus)", radia: 705, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "RODEO (Rodeus amarus)", radia: 259, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "ABRAMIDE (Abramis brama)", radia: 260, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "LUCCIO PERCA (Stizostedion lucioperca)", radia: 261, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "BREME (Abramis brama)", radia: 262, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "PESCE GATTO MACULATO (Ictalurus punctatus)", radia: 592, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "LUCCIO (Esox lucius)", radia: 144, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "PERSICO (Perca fluviatilis)", radia: 145, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "PESCE GATTO (Ictalurus melas)", radia: 1024, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "PIGO (Rutilus pigus)", radia: 706, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "SAVETTA (Chondrostoma soetta)", radia: 699, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "SCARDOLA (Scardinus erythrophthalmus)", radia: 707, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "SILURO (Silurus glanis)", radia: 708, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "TINCA (Tinca tinca)", radia: 709, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "TRIOTTO (Rutilus aula)", radia: 710, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "TROTA (Salmo trutta)", radia: 143, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "ACERINA (Gymnocephalus cernuus)", radia: 765, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "RUTILO o GARDON (Rutilus rutilus)", radia: 766, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE ACQUA DOLCE" ).try(:id), title: "SALMERINO DI FONTANA (Salvelinus fontinalis)", radia: 767, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "ACCIUGA o ALICE (Engraulis encrasicholus)", radia: 219, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "AGUGLIA (Belone belone)", radia: 227, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "ALALUNGA (Thunnus alalunga)", radia: 232, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "CERNIA (Epinephelus guaza)", radia: 236, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "MERLANO O MORO (Merlangius merlangus)", radia: 241, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "GHIOZZO PAGANELLO O MORA (Gobius paganellus)", radia: 242, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "PAPALINA (Sprattus sprattus)", radia: 263, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "PESCE SPADA (Xiphaias gladius)", radia: 229, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "RICCIOLA (Seriola dumerili)", radia: 230, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "SOGLIOLA COMUNE (Solea solea)", radia: 518, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "TOMBARELLO (Auxis thazard)", radia: 231, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "BOGA (Boops boops)", radia: 711, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "BRANZINO (Dicentrarchus labrax)", radia: 713, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "CEFALO (Mugil cephalus)", radia: 714, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "GHIOZZO (Gobius niger)", radia: 715, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "GRONCO (Groncus vulgaris)", radia: 716, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "LATTERINO (Atherina boyeri)", radia: 1086, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "MENOLA (Spicara maena)", radia: 717, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "MERLUZZO (Gadus morhua)", radia: 147, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "NASELLO (Merluccius merluccius)", radia: 1317, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "ORATA (Sparus aurata)", radia: 149, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "PAGELLO o FRAGOLINO (Pagellus erythrinus)", radia: 1085, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "PAGELLO (Pagellus bogaraveo)", radia: 226, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "PALOMBO (Mustelus mustelus)", radia: 1126, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "POTASSOLO (Micromesistius poutassou)", radia: 718, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "SALMONE (Salmo salar)", radia: 735, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "SALPA (Sarpa salpa)", radia: 1313, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "SARDINA (Sardina pilchardus)", radia: 146, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "SGOMBRO (Scomber scombrus)", radia: 148, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "SUGARELLO (Trachurus trachurus)", radia: 712, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "TONNO (Tonnus thynnus)", radia: 150, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "TRIGLIA (Mullus surmuletus)", radia: 1314, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "VERDESCA (Prionace glauca)", radia: 719, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "GALLINELLA o CAPONE (Chelidonichthys lucernus) ", radia: 728, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PESCE DI MARE" ).try(:id), title: "RANA PESCATRICE o CODA DI ROSPO (Lophius piscatorius)", radia: 741, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "COZZA (Mytilus edulis)", radia: 151, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "COZZA (Mytilus galloprovincialis)", radia: 152, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "VONGOLA (Chamelea gallina)", radia: 153, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "VONGOLA FILIPPINA (Tapes philippinarum)", radia: 154, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "VONGOLA VERACE (Tapes decussatus)", radia: 155, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "POLPO (Octopus vulgaris)", radia: 156, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "MOSCARDINO (Moscardinus avellanarius)", radia: 157, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "FASOLARI (Callista chione)", radia: 243, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "MURICI (Murici spp)", radia: 244, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "CUORE (Cerastoderma spp)", radia: 245, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "CALAMARO (Loligo forbesi)", radia: 720, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "CALAMARO (Loligo vulgaris)", radia: 721, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "CANESTRELLI (Chlamys varia)", radia: 722, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "SCAPHARCA (Scapharca inaequivalvis)", radia: 723, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "SEPPIA (Sepia officinalis)", radia: 724, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "MOLLUSCHI" ).try(:id), title: "OSTRICA GIAPPONESE (Crassostrea gigas)", radia: 595, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CROSTACEI" ).try(:id), title: "GAMBERO ROSSO (Aristeus antennatus)", radia: 158, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CROSTACEI" ).try(:id), title: "SCAMPO (Nephrops norvegicus)", radia: 159, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CROSTACEI" ).try(:id), title: "GRANCHIO (Carcinus mediterraneus)", radia: 725, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PRODOTTI ALVEARE" ).try(:id), title: "MIELE", radia: 160, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PRODOTTI ALVEARE" ).try(:id), title: "MIELE DI ACACIA", radia: 161, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PRODOTTI ALVEARE" ).try(:id), title: "CERA", radia: 162, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PRODOTTI ALVEARE" ).try(:id), title: "MIELE MILLEFIORI", radia: 220, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PRODOTTI ALVEARE" ).try(:id), title: "MIELE DI MELATA", radia: 228, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PRODOTTI ALVEARE" ).try(:id), title: "MIELE DI CASTAGNO", radia: 216, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PRODOTTI ALVEARE" ).try(:id), title: "MIELE DI TIGLIO", radia: 732, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PASTO COMPLETO" ).try(:id), title: "PASTO COMPLETO DI MENSA AZIENDALE", radia: 163, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PASTO COMPLETO" ).try(:id), title: "PASTO COMPLETO DI ASILO INFANTILE", radia: 164, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PASTO COMPLETO" ).try(:id), title: "PASTO COMPLETO DI ASILO NIDO", radia: 165, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PASTO COMPLETO" ).try(:id), title: "PASTO COMPLETO DI CENTRO PRODUZIONE PASTI", radia: 264, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PASTO COMPLETO" ).try(:id), title: "PASTO COMPLETO DI MENSA SCOLASTICA", radia: 265, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "PASTO COMPLETO" ).try(:id), title: "DIETA MISTA", radia: 166, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LATTE" ).try(:id), title: "LATTE VACCINO INTERO CRUDO", radia: 167, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LATTE" ).try(:id), title: "LATTE VACCINO INTERO PASTORIZZATO", radia: 168, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LATTE" ).try(:id), title: "LATTE VACCINO INTERO UHT", radia: 169, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LATTE" ).try(:id), title: "LATTE VACCINO PARZIALMENTE SCREMATO PASTORIZZATO", radia: 170, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LATTE" ).try(:id), title: "LATTE VACCINO PARZIALMENTE SCREMATO UHT", radia: 171, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LATTE" ).try(:id), title: "LATTE VACCINO INTERO IN POLVERE", radia: 172, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LATTE" ).try(:id), title: "LATTE OVINO CRUDO", radia: 173, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LATTE" ).try(:id), title: "LATTE OVINO INTERO PASTORIZZATO", radia: 174, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LATTE" ).try(:id), title: "LATTE IN POLVERE LATTANTI", radia: 175, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LATTE" ).try(:id), title: "LATTE LIQUIDO LATTANTI", radia: 176, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LATTE" ).try(:id), title: "LATTE CAPRINO  INTERO PASTORIZZATO", radia: 726, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LATTE" ).try(:id), title: "LATTE CAPRINO INTERO CRUDO", radia: 727, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LATTE" ).try(:id), title: "LATTE VACCINO IN POLVERE SCREMATO", radia: 729, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LATTE" ).try(:id), title: "LATTE DI BUFALA CRUDO", radia: 597, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "LATTE" ).try(:id), title: "LATTE VACCINO SCREMATO UHT", radia: 730, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DERIVATI DEL LATTE" ).try(:id), title: "FORMAGGIO GRANA", radia: 177, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DERIVATI DEL LATTE" ).try(:id), title: "YOGURT", radia: 178, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DERIVATI DEL LATTE" ).try(:id), title: "YOGURT BIANCO", radia: 178, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DERIVATI DEL LATTE" ).try(:id), title: "YOGURT ALLA FRUTTA ", radia: 266, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DERIVATI DEL LATTE" ).try(:id), title: "BURRO", radia: 179, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DERIVATI DEL LATTE" ).try(:id), title: "SIERO DI LATTE", radia: 180, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "DERIVATI DEL LATTE" ).try(:id), title: "FORMAGGIO PARMIGIANO REGGIANO", radia: 306, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUA POTABILE" ).try(:id), title: "ACQUA POTABILE DI RETE DI DISTRIBUZIONE", radia: 181, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUA POTABILE" ).try(:id), title: "ACQUA POTABILE SUPERFICIALE (NCFC)", radia: 267, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUA POTABILE" ).try(:id), title: "ACQUA POTABILE SUPERFICIALE (RESINE MISTE)", radia: 268, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUA POTABILE" ).try(:id), title: "ACQUA POTABILE MISTA (NCFC)", radia: 269, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUA POTABILE" ).try(:id), title: "ACQUA POTABILE MISTA (RESINE MISTE)", radia: 270, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUA POTABILE" ).try(:id), title: "ACQUA POTABILE SOTTERRANEA (FILTRI)", radia: 593, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUA POTABILE" ).try(:id), title: "ACQUA POTABILE SOTTERRANEA (NCFC)", radia: 594, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUA POTABILE" ).try(:id), title: "ACQUA POTABILE SUPERFICIALE", radia: 182, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUA POTABILE" ).try(:id), title: "ACQUA POTABILE IMBOTTIGLIATA", radia: 183, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUA POTABILE" ).try(:id), title: "ACQUA POTABILE SOTTERRANEA", radia: 184, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUA POTABILE" ).try(:id), title: "ACQUA POTABILE MISTA", radia: 1148, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUA POTABILE" ).try(:id), title: "ACQUA POTABILE D'IMPIANTO DI TRATTAMENTO", radia: 185, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUA D'IMPIANTO DI DEPURAZIONE" ).try(:id), title: "ACQUA DI SCARICO", radia: 186, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUA D'IMPIANTO DI DEPURAZIONE" ).try(:id), title: "ACQUA DEPURATA", radia: 187, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ACQUA D'IMPIANTO DI DEPURAZIONE" ).try(:id), title: "FANGO DEPURATORE", radia: 188, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ALIMENTI INFANZIA" ).try(:id), title: "OMOGENEIZZATO CARNE", radia: 189, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ALIMENTI INFANZIA" ).try(:id), title: "OMOGENEIZZATO FRUTTA", radia: 190, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ALIMENTI INFANZIA" ).try(:id), title: "BISCOTTI", radia: 191, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ALIMENTI INFANZIA" ).try(:id), title: "PASTINA PRIMA INFANZIA", radia: 762, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BACCHE SELVATICHE" ).try(:id), title: "MORE", radia: 196, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BACCHE SELVATICHE" ).try(:id), title: "LAMPONI", radia: 197, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BACCHE SELVATICHE" ).try(:id), title: "MIRTILLI", radia: 198, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BACCHE SELVATICHE" ).try(:id), title: "MIRTILLO NERO", radia: 739, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BACCHE SELVATICHE" ).try(:id), title: "MIRTILLO ROSSO", radia: 740, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BACCHE SELVATICHE" ).try(:id), title: "FRAGOLE DI BOSCO", radia: 199, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "BACCHE SELVATICHE" ).try(:id), title: "RIBES", radia: 731, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "ZUCCHERO" ).try(:id), title: "ZUCCHERO DA BARBABIETOLA", radia: 205, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CONFETTURA" ).try(:id), title: "CONFETTURA DI FRAGOLE", radia: 207, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CONFETTURA" ).try(:id), title: "CONFETTURA DI CILIEGIE", radia: 208, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CONFETTURA" ).try(:id), title: "CONFETTURA DI ALBICOCCHE", radia: 209, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CONFETTURA" ).try(:id), title: "CONFETTURA DI PESCHE", radia: 210, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CONFETTURA" ).try(:id), title: "CONFETTURA DI SUSINE", radia: 211, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CONFETTURA" ).try(:id), title: "CONFETTURA DI MIRTILLI", radia: 212, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "COMBUSTIBILI" ).try(:id), title: "CENERE DI PELLET LEGNO", radia: 1345, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "COMBUSTIBILI" ).try(:id), title: "PELLET LEGNO", radia: 1366, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "COMBUSTIBILI" ).try(:id), title: "LEGNO PRESSATO", radia: 222, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "COMBUSTIBILI" ).try(:id), title: "FULIGGINE", radia: 223, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "COMBUSTIBILI" ).try(:id), title: "CENERE DI LEGNO", radia: 224, author: 'System')
MatrixType.create( pid: MatrixType.unscoped.find_or_create_by( title: "CONTAMINAZIONE SUPERFICIALE" ).try(:id), title: "SMEAR TEST", radia: 225, author: 'System')